---
- name: install docker and required s/w's
  hosts: all
  tasks:
    - name: install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: download docker script, exicute it and install docker_py
      shell: "{{item}}"
      with_items:  
        - curl -fsSL https://get.docker.com -o install-docker.sh
        - sudo sh install-docker.sh
        - pip3 install docker_py
