---
- name: create 8 nginx containers
  hosts: all
  tasks:
    - name: create 8 containers
      docker_container:
        image: nginx
        name: "container{{item}}"
      with_sequence: count=8
